### ISSUE TITLE
Contao 4.6 in Symfony 4 services has to be "public" 

### ISSUE THREAD

**Issue by bzaiser** [pdir/contao-theme-helper-bundle#1]
please add "public: true"

services:
    theme_helper.listener.insert_tags:
        class: Pdir\ThemeHelperBundle\EventListener\InsertTagsListener
        **public: true**
        arguments:
            - "@contao.framework"

Thanks

Bernd

**Comment by MDevster** [comment]
fixed in 1.1.0
